const Books = [
	{
		id: 1,
		department: "Department of CSE",
		semester: "1st Semester",
		title: "Introduction to Computer System",
		author: "John Smith",
		publisher: "TechBooks Inc.",
	},
	{
		id: 2,
		department: "Department of CSE",
		semester: "1st Semester",
		title: "Fundamentals of Electric Engineering",
		author: "Sarah Johnson",
		publisher: "ElectricPublish",
	},
	{
		id: 3,
		department: "Department of CSE",
		semester: "1st Semester",
		title: "Fundamentals of Mathematics",
		author: "Chris Davis",
		publisher: "MathTech Inc.",
	},
	{
		id: 4,
		department: "Department of CSE",
		semester: "1st Semester",
		title: "Waves, Optics & Thermodynamics",
		author: "David Miller",
		publisher: "WaveBooks",
	},
	{
		id: 5,
		department: "Department of CSE",
		semester: "2nd Semester",
		title: "Structured Programming Language C",
		author: "Eve Anderson",
		publisher: "CodePublish",
	},
	{
		id: 6,
		department: "Department of CSE",
		semester: "2nd Semester",
		title: "Discrete Mathematics",
		author: "Michael Roberts",
		publisher: "MathTech Inc.",
	},
	{
		id: 7,
		department: "Department of CSE",
		semester: "2nd Semester",
		title: "Differential and Integral Calculus",
		author: "Olivia Davis",
		publisher: "MathTech Inc.",
	},
	{
		id: 8,
		department: "Department of CSE",
		semester: "2nd Semester",
		title: "Electricity, Magnetism & Modern Physics",
		author: "Jason Lee",
		publisher: "PhysicsTech",
	},
	{
		id: 9,
		department: "Department of CSE",
		semester: "3rd Semester",
		title: "Engineering Chemistry",
		author: "Daniel Harris",
		publisher: "ChemTech Inc.",
	},
	{
		id: 10,
		department: "Department of CSE",
		semester: "3rd Semester",
		title: "Object Oriented Programming Language",
		author: "Emma Williams",
		publisher: "CodeCrafters",
	},
	{
		id: 11,
		department: "Department of CSE",
		semester: "3rd Semester",
		title: "Electronic Devices and Circuits",
		author: "Liam Turner",
		publisher: "ElectroTech Inc.",
	},
	{
		id: 12,
		department: "Department of CSE",
		semester: "3rd Semester",
		title: "Ordinary and Partial Differential Equations",
		author: "Sophia Davis",
		publisher: "MathTech Inc.",
	},
	{
		id: 13,
		department: "Department of CSE",
		semester: "3rd Semester",
		title: "Probability and Statistics",
		author: "Benjamin Clark",
		publisher: "StatsPublish",
	},
	{
		id: 14,
		department: "Department of CSE",
		semester: "4th Semester",
		title: "Digital Logic Design",
		author: "Ethan Smith",
		publisher: "LogicBooks",
	},
	{
		id: 15,
		department: "Department of CSE",
		semester: "4th Semester",
		title: "Web Technology",
		author: "Grace Johnson",
		publisher: "WebTech Inc.",
	},
	{
		id: 16,
		department: "Department of CSE",
		semester: "4th Semester",
		title: "Data Structure",
		author: "Ethan Thompson",
		publisher: "TechBooks Inc.",
	},
	{
		id: 17,
		department: "Department of CSE",
		semester: "4th Semester",
		title: "Data Communication I",
		author: "Sophia Miller",
		publisher: "DataComm Publishing",
	},
	{
		id: 18,
		department: "Department of CSE",
		semester: "4th Semester",
		title: "Coordinate Geometry and Vector Analysis",
		author: "Liam Clark",
		publisher: "GeometryTech Press",
	},
	{
		id: 19,
		department: "Department of CSE",
		semester: "5th Semester",
		title: "Digital Electronics and Pulse Techniques",
		author: "Olivia Williams",
		publisher: "PulseTech Inc.",
	},
	{
		id: 20,
		department: "Department of CSE",
		semester: "5th Semester",
		title: "Algorithms",
		author: "Michael Davis",
		publisher: "AlgoPublishers",
	},
	{
		id: 21,
		department: "Department of CSE",
		semester: "5th Semester",
		title: "Database Management System",
		author: "Jason Turner",
		publisher: "DBMS Books",
	},
	{
		id: 22,
		department: "Department of CSE",
		semester: "5th Semester",
		title: "Theory Of Computation",
		author: "Sophie Clark",
		publisher: "TheoryTech Inc.",
	},
	{
		id: 23,
		department: "Department of CSE",
		semester: "5th Semester",
		title: "Assembly Language",
		author: "Benjamin Turner",
		publisher: "AssemblyBooks",
	},
	{
		id: 24,
		department: "Department of CSE",
		semester: "5th Semester",
		title: "Data Communication II",
		author: "David Harris",
		publisher: "DataComm Publishers",
	},
	{
		id: 25,
		department: "Department of CSE",
		semester: "6th Semester",
		title: "Numerical Methods and Analysis",
		author: "Eve Anderson",
		publisher: "NumericTech Inc.",
	},
	{
		id: 26,
		department: "Department of CSE",
		semester: "6th Semester",
		title: "Computer Architecture",
		author: "Alice Johnson",
		publisher: "Blue Sky Publications",
	},
	{
		id: 27,
		department: "Department of CSE",
		semester: "6th Semester",
		title: "Information System Design",
		author: "David Smith",
		publisher: "Sunrise Books",
	},
	{
		id: 28,
		department: "Department of CSE",
		semester: "6th Semester",
		title: "Compiler",
		author: "Emily Brown",
		publisher: "Golden Press",
	},
	{
		id: 29,
		department: "Department of CSE",
		semester: "6th Semester",
		title: "Computer Network",
		author: "Matthew Taylor",
		publisher: "Evergreen Publishing",
	},
	{
		id: 30,
		department: "Department of CSE",
		semester: "7th Semester",
		title: "Microprocessor and Microcontrollers",
		author: "Sophia Anderson",
		publisher: "TechKnowledge Books",
	},
	{
		id: 31,
		department: "Department of CSE",
		semester: "7th Semester",
		title: "Operating System",
		author: "Daniel Clark",
		publisher: "Swift Publishing",
	},
	{
		id: 32,
		department: "Department of CSE",
		semester: "7th Semester",
		title: "Software Engineering",
		author: "Olivia Walker",
		publisher: "Infinite Books",
	},
	{
		id: 33,
		department: "Department of CSE",
		semester: "8th Semester",
		title: "Artificial Intelligence",
		author: "Michael Davis",
		publisher: "Tech Press",
	},
	{
		id: 34,
		department: "Department of EEE",
		semester: "1st Semester",
		title: "Computer Fundamental and Web Technology",
		author: "Alice Davis",
		publisher: "TechWeb Press",
	},
	{
		id: 35,
		department: "Department of EEE",
		semester: "1st Semester",
		title: "Fundamental Mathematics",
		author: "Michael Johnson",
		publisher: "MathSolutions Publishing",
	},
	{
		id: 36,
		department: "Department of EEE",
		semester: "1st Semester",
		title: "Engineering Physics I",
		author: "Robert Turner",
		publisher: "TechBook Inc.",
	},
	{
		id: 37,
		department: "Department of EEE",
		semester: "1st Semester",
		title: "Electrical Circuit",
		author: "Sophie Miller",
		publisher: "ElectroPress",
	},
	{
		id: 38,
		department: "Department of EEE",
		semester: "1st Semester",
		title: "English I",
		author: "Daniel Harris",
		publisher: "Infinite Publications",
	},
	{
		id: 39,
		department: "Department of EEE",
		semester: "2nd Semester",
		title: "Differential and Integral Calculus",
		author: "Laura Smith",
		publisher: "Enlighten Books",
	},
	{
		id: 40,
		department: "Department of EEE",
		semester: "2nd Semester",
		title: "Engineering Physics II",
		author: "Andrew Davis",
		publisher: "Spark Publications",
	},
	{
		id: 41,
		department: "Department of EEE",
		semester: "2nd Semester",
		title: "Electrical Circuit II",
		author: "Olivia Turner",
		publisher: "PowerHouse Books",
	},
	{
		id: 42,
		department: "Department of EEE",
		semester: "2nd Semester",
		title: "Engineering Drawing",
		author: "Matthew Johnson",
		publisher: "Visualize Press",
	},
	{
		id: 43,
		department: "Department of EEE",
		semester: "3rd Semester",
		title: "Ordinary and Partial Differential Calculus",
		author: "Sophia Adams",
		publisher: "MathSolutions Publishing",
	},
	{
		id: 44,
		department: "Department of EEE",
		semester: "3rd Semester",
		title: "Engineering Chemistry",
		author: "David Mitchell",
		publisher: "ScienceHub Publishers",
	},
	{
		id: 45,
		department: "Department of EEE",
		semester: "3rd Semester",
		title: "Electronic Circuit I",
		author: "Rachel Clark",
		publisher: "ElectroTech Books",
	},
	{
		id: 46,
		department: "Department of EEE",
		semester: "3rd Semester",
		title: "Electrical Machines I",
		author: "Mark Miller",
		publisher: "ElecPrime Publications",
	},
	{
		id: 47,
		department: "Department of EEE",
		semester: "3rd Semester",
		title: "Computer Programming",
		author: "Natalie Anderson",
		publisher: "CodeCraft Press",
	},
	{
		id: 48,
		department: "Department of EEE",
		semester: "4th Semester",
		title: "Probability and Statistics",
		author: "Paul Harrison",
		publisher: "StatInnovate Publishing",
	},
	{
		id: 49,
		department: "Department of EEE",
		semester: "4th Semester",
		title: "Digital Electronics",
		author: "William Turner",
		publisher: "DigitalWiz Books",
	},
	{
		id: 50,
		department: "Department of EEE",
		semester: "4th Semester",
		title: "Electronic Circuit II",
		author: "Emily Harris",
		publisher: "ElectroTech Books",
	},
	{
		id: 51,
		department: "Department of EEE",
		semester: "4th Semester",
		title: "Electrical Machines II",
		author: "Daniel Scott",
		publisher: "ElecPrime Publications",
	},
	{
		id: 52,
		department: "Department of EEE",
		semester: "4th Semester",
		title: "Coordinate and Geometry Vector Analysis",
		author: "Jessica Turner",
		publisher: "MathSolutions Publishing",
	},
	{
		id: 53,
		department: "Department of EEE",
		semester: "5th Semester",
		title: "Electronic Measurement and Instrument",
		author: "Alice Johnson",
		publisher: "ElectroPress",
	},
	{
		id: 54,
		department: "Department of EEE",
		semester: "5th Semester",
		title: "Fundamentals of Machine Learning",
		author: "Bob Smith",
		publisher: "TechBooks Inc.",
	},
	{
		id: 55,
		department: "Department of EEE",
		semester: "5th Semester",
		title: "Numerical Method and Analysis",
		author: "Charlie Davis",
		publisher: "Numerix Publications",
	},
	{
		id: 56,
		department: "Department of EEE",
		semester: "5th Semester",
		title: "Electromagnetic Fields and Waves",
		author: "David Roberts",
		publisher: "WaveTech Publishers",
	},
	{
		id: 57,
		department: "Department of EEE",
		semester: "5th Semester",
		title: "Signals and Systems",
		author: "Eve Adams",
		publisher: "SignalBooks",
	},
	{
		id: 58,
		department: "Department of EEE",
		semester: "6th Semester",
		title: "Numerical Methods and Analysis II",
		author: "Frank Miller",
		publisher: "MathTech Press",
	},
	{
		id: 59,
		department: "Department of EEE",
		semester: "6th Semester",
		title: "Communication Theory",
		author: "Grace Wilson",
		publisher: "Communica Publications",
	},
	{
		id: 60,
		department: "Department of EEE",
		semester: "6th Semester",
		title: "Microprocessor and Interfacing",
		author: "Harry Thompson",
		publisher: "TechFusion Books",
	},
	{
		id: 61,
		department: "Department of EEE",
		semester: "6th Semester",
		title: "Industrial Electronics",
		author: "Ivy Lewis",
		publisher: "IndustrialTech Press",
	},
	{
		id: 62,
		department: "Department of EEE",
		semester: "7th Semester",
		title: "Solid State Devices",
		author: "James Clark",
		publisher: "SolidState Publishers",
	},
	{
		id: 63,
		department: "Department of EEE",
		semester: "7th Semester",
		title: "Digital Signal Processing",
		author: "Kate Anderson",
		publisher: "SignalTech Books",
	},
	{
		id: 64,
		department: "Department of EEE",
		semester: "7th Semester",
		title: "Electrical Service Design",
		author: "Liam Turner",
		publisher: "ServiceTech Press",
	},
	{
		id: 65,
		department: "Department of EEE",
		semester: "7th Semester",
		title: "Control Systems",
		author: "Mark Davis",
		publisher: "ControlTech Publishers",
	},
	{
		id: 66,
		department: "Department of EEE",
		semester: "8th Semester",
		title: "Digital Integrated Circuit Design",
		author: "Nancy Taylor",
		publisher: "DigitalCircuits Inc.",
	},
	{
		id: 67,
		department: "Department of EEE",
		semester: "8th Semester",
		title: "Software Engineering",
		author: "Oscar Miller",
		publisher: "SoftTech Publications",
	},
];

export default Books;
