const Books = [
	{
		id: 1,
		department: "Department of CSE",
		semester: "1st Semester",
		title: "Structured Programming Language",
		author: "John Haddon",
		publisher: "New York Press",
	},
	{
		id: 2,
		department: "Department of CSE",
		semester: "2nd Semester",
		title: "Data Structures and Algorithms",
		author: "Alice Smith",
		publisher: "Tech Publications",
	},
	{
		id: 3,
		department: "Department of ECE",
		semester: "3rd Semester",
		title: "Digital Electronics",
		author: "David Johnson",
		publisher: "ECE Press",
	},
	{
		id: 4,
		department: "Department of EE",
		semester: "4th Semester",
		title: "Circuit Analysis",
		author: "Michael Davis",
		publisher: "EE Publishing",
	},
	{
		id: 5,
		department: "Department of Mech",
		semester: "5th Semester",
		title: "Thermodynamics",
		author: "Emily Brown",
		publisher: "Mechanical Books Inc.",
	},
	{
		id: 6,
		department: "Department of Civil",
		semester: "6th Semester",
		title: "Structural Analysis",
		author: "Thomas Clark",
		publisher: "Civil Engineering Publications",
	},
	{
		id: 7,
		department: "Department of IT",
		semester: "7th Semester",
		title: "Database Management Systems",
		author: "Sarah Adams",
		publisher: "IT Press",
	},
	{
		id: 8,
		department: "Department of CSE",
		semester: "8th Semester",
		title: "Artificial Intelligence",
		author: "Andrew Wilson",
		publisher: "CSE Publishing",
	},
	{
		id: 9,
		department: "Department of EEE",
		semester: "9th Semester",
		title: "Power Systems",
		author: "Daniel Brown",
		publisher: "Power Systems Books",
	},
	{
		id: 10,
		department: "Department of Mech",
		semester: "10th Semester",
		title: "Machine Design",
		author: "Jessica Miller",
		publisher: "Mechanical Engineering Press",
	},
	{
		id: 11,
		department: "Department of Civil",
		semester: "11th Semester",
		title: "Transportation Engineering",
		author: "Paul Anderson",
		publisher: "Civil Engineering Publications",
	},
	{
		id: 12,
		department: "Department of IT",
		semester: "12th Semester",
		title: "Software Engineering",
		author: "Lisa Johnson",
		publisher: "IT Press",
	},
];

export default Books;
